# Generated by Django 4.1 on 2023-08-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('CollectionId', models.BigAutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=100)),
                ('CustomerId', models.BigIntegerField()),
                ('CollectionNotes', models.TextField()),
                ('PaymentMode', models.CharField(max_length=200)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('ReceivedDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerId', models.BigAutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=500)),
                ('ContactPerson', models.CharField(blank=True, max_length=500)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Email', models.CharField(blank=True, max_length=300)),
                ('PhoneNumber1', models.CharField(max_length=200)),
                ('PhoneNumber2', models.CharField(blank=True, max_length=200)),
                ('Pincode', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=300)),
                ('UserId', models.CharField(max_length=100)),
                ('TotalPendingAmount', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderId', models.BigAutoField(primary_key=True, serialize=False)),
                ('CustomerId', models.BigIntegerField()),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=50)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=50)),
                ('SubTotal', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=50)),
                ('DiscountAmount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('OrderNotes', models.TextField()),
                ('OrderStatus', models.CharField(max_length=100)),
                ('ProductIds', models.CharField(max_length=500)),
                ('Quantities', models.CharField(max_length=500)),
                ('UserId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(max_length=200)),
                ('Price1', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Price2', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Price3', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.BigAutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=200)),
                ('KG', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.BigAutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=300)),
                ('Password', models.CharField(max_length=300)),
                ('Name', models.CharField(max_length=500)),
                ('PhoneNumber', models.CharField(max_length=200)),
                ('Level', models.IntegerField()),
            ],
        ),
    ]
