# Generated by Django 4.1 on 2024-03-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
